### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by akshay-ajackus** [Laravel-Backpack/revise-operation#11]
I am using backpacker for admin panel in my project. I m using revise-operation for tracking history of CRUD operations. The problem is that in revise blade foreign table history is not showing but it is getting updated in database.

Table Structure -

Company - id, name, address, etc.

CompanyParameterValues - id, company_id, value, text, etc.

Here Company has many parameters and CompanyParameterValue belongTo one Company. I want to show CompanyParameterValue edit history in Company revision blade.

Thanks in Advance.

**Comment by promatik** [comment]
Hi @akshay-ajackus `revisionable` only stores the changes of the model your in, not it's relationships.

In your case `CompanyParameterValue` is another Model.

My suggestion to accomplish this is to use `RevisionableTrait` on `CompanyParameterValue` model to log the revisions for that too. Then override `listRevisions` (from `Backpack\ReviseOperation\ReviseOperation`) method on your `Company` model in a way you'll display changes from both models.

Please let us know if you've figure out a way to solve this 🙌
