### ISSUE TITLE
Where to place custom revision-operation views?

### ISSUE THREAD

**Issue by kfulk14** [Laravel-Backpack/revise-operation#4]
Hi, 

I where within resources/views/vendor/backpack/ directory would I place revisions blade files (revision_timeline.blade.php and revisions.blade.php ) to override the defaults being pulled in from the vendor folder?

Thanks

**Comment by tabacitu** [comment]
Oups - looks like we missed that feature for this package. Thanks for the heads-up @kfulk14 , it's done thanks to #5 . You can now put your blade files inside `resources/views/vendor/backpack/revise-operation` and they will be picked up instead of the ones in the package.

Cheers!

**Comment by kfulk14** [comment]
@tabacitu thanks for the update much appreciated.
