### ISSUE TITLE
[Feature Request] Allow certain users to Restore revision depending on permission or something else

### ISSUE THREAD

**Issue by jrbecart** [Laravel-Backpack/revise-operation#9]
# Feature Request

### What's the feature you think this package should have?

Possibility to remove the /restore route **or** add another operation name to manage permission differently from the list route.
Be allowed to use permission.

```php
protected function setupReviseRoutes($segment, $routeName, $controller)
    {
        Route::get($segment.'/{id}/revise', [
            'as' => $routeName.'.listRevisions',
            'uses' => $controller.'@listRevisions',
            'operation' => 'reviseList', // new operation name...
        ]);

        Route::post($segment.'/{id}/revise/{revisionId}/restore', [
            'as' => $routeName.'.restoreRevision',
            'uses' => $controller.'@restoreRevision',
            'operation' => 'reviseRestore', // new operation name
        ]);
    }
```

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Yes

**Comment by tabacitu** [comment]
@jrbecart at first I thought this would be a good idea. And in theory it shouldn't be difficult at all to achieve:
- we add a setting inside the `config/backpack/crud.php` config file, for the `revise` operation;
- check that config first thing before loading the Restore button, or doing the Restore action;

But then I though - you should be able to do the exact same inside a `setupReviseOperation()` method. Backpack will automatically call it if it's there. And now that I think of it, it should be pretty easy and customizable over there to check the combination of user/route/permission and abort if something's not ok. MUCH easier than bloating the package with this additional logic. So something like this should do it:

```php
public function setupReviseOperation() {
    // if route operation is `revise` AND
    // the called route name ends with `restoreRevision` AND
    // the user doesn't have the permission to do this
    // TODO: abort
}
```

Let me know what you think.
Cheers!

**Comment by jrbecart** [comment]
@tabacitu Thanks! I was thinking at the same solution and I will probably doing it that way. 
It's just that I have many controllers... :( 

My other solution was to do it in `custom.php` but I was unable to use the wildcard in the route so instead of overriding all routes I will do it in all my controllers. 

```php
// I attempted to replace myroute with wildcard such as {any}, {any?}, {any:.*} 
// to override all routes at once but with no luck
Route::post('myroute/{id}/revise/{revisionId}/restore', function () {
     abort(404);
});
```

Anyway you are right that's probably the easiest way and this will avoid to bloat the package.

**Comment by tabacitu** [comment]
👍 if you need it across many CrudControllers, you can:
- create a Trait with that method, something like `ReviseOperationRestoreOnlyIfPermission`
- just use the trait right after you use the `ReviseOperation` trait

Personally I'd put that inside `app/Http/Controllers/Admin/Operations` but to each his own.
Hope it helps!
